// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpilibc/generate_hids.py. DO NOT MODIFY

#include "XboxController.h"
#include "BooleanEvent.h"

//wpilibcExamples/src/main/cpp/examples/TankDriveXboxController/cpp/Robot.cpp#L6
//https://docs.wpilib.org/en/stable/docs/software/basic-programming/joystick.html

XboxController::XboxController(int port) : GenericHID(port) {
}

double XboxController::getLeftX() const {
    return getRawAxis(Axis::kLeftX);
}

double XboxController::getRightX() const {
    return getRawAxis(Axis::kRightX);
}

double XboxController::getLeftY() const {
    return getRawAxis(Axis::kLeftY);
}

double XboxController::getRightY() const {
    return getRawAxis(Axis::kRightY);
}

double XboxController::getLeftTriggerAxis() const {
    return getRawAxis(Axis::kLeftTrigger);
}

BooleanEvent XboxController::leftTrigger(double threshold, EventLoop *loop) const {
    return BooleanEvent(loop, [this, threshold] { return this->getLeftTriggerAxis() > threshold; });
}

BooleanEvent XboxController::leftTrigger(EventLoop *loop) const {
    return this->leftTrigger(0.5, loop);
}

double XboxController::getRightTriggerAxis() const {
    return getRawAxis(Axis::kRightTrigger);
}

BooleanEvent XboxController::rightTrigger(double threshold, EventLoop *loop) const {
    return BooleanEvent(loop, [this, threshold] { return this->getRightTriggerAxis() > threshold; });
}

BooleanEvent XboxController::rightTrigger(EventLoop *loop) const {
    return this->rightTrigger(0.5, loop);
}

bool XboxController::getAButton() const {
    return getRawButton(Button::kA);
}

bool XboxController::getAButtonPressed() {
    return getRawButtonPressed(Button::kA);
}

bool XboxController::getAButtonReleased() {
    return getRawButtonReleased(Button::kA);
}

BooleanEvent XboxController::A(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getAButton(); });
}

bool XboxController::getBButton() const {
    return getRawButton(Button::kB);
}

bool XboxController::getBButtonPressed() {
    return getRawButtonPressed(Button::kB);
}

bool XboxController::getBButtonReleased() {
    return getRawButtonReleased(Button::kB);
}

BooleanEvent XboxController::B(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getBButton(); });
}

bool XboxController::getXButton() const {
    return getRawButton(Button::kX);
}

bool XboxController::getXButtonPressed() {
    return getRawButtonPressed(Button::kX);
}

bool XboxController::getXButtonReleased() {
    return getRawButtonReleased(Button::kX);
}

BooleanEvent XboxController::X(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getXButton(); });
}

bool XboxController::getYButton() const {
    return getRawButton(Button::kY);
}

bool XboxController::getYButtonPressed() {
    return getRawButtonPressed(Button::kY);
}

bool XboxController::getYButtonReleased() {
    return getRawButtonReleased(Button::kY);
}

BooleanEvent XboxController::Y(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getYButton(); });
}

bool XboxController::getLeftBumperButton() const {
    return getRawButton(Button::kLeftBumper);
}

bool XboxController::getLeftBumperButtonPressed() {
    return getRawButtonPressed(Button::kLeftBumper);
}

bool XboxController::getLeftBumperButtonReleased() {
    return getRawButtonReleased(Button::kLeftBumper);
}

BooleanEvent XboxController::leftBumper(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getLeftBumperButton(); });
}

bool XboxController::getRightBumperButton() const {
    return getRawButton(Button::kRightBumper);
}

bool XboxController::getRightBumperButtonPressed() {
    return getRawButtonPressed(Button::kRightBumper);
}

bool XboxController::getRightBumperButtonReleased() {
    return getRawButtonReleased(Button::kRightBumper);
}

BooleanEvent XboxController::rightBumper(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getRightBumperButton(); });
}

bool XboxController::getBackButton() const {
    return getRawButton(Button::kBack);
}

bool XboxController::getBackButtonPressed() {
    return getRawButtonPressed(Button::kBack);
}

bool XboxController::getBackButtonReleased() {
    return getRawButtonReleased(Button::kBack);
}

BooleanEvent XboxController::back(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getBackButton(); });
}

bool XboxController::getStartButton() const {
    return getRawButton(Button::kStart);
}

bool XboxController::getStartButtonPressed() {
    return getRawButtonPressed(Button::kStart);
}

bool XboxController::getStartButtonReleased() {
    return getRawButtonReleased(Button::kStart);
}

BooleanEvent XboxController::start(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getStartButton(); });
}

bool XboxController::getLeftStickButton() const {
    return getRawButton(Button::kLeftStick);
}

bool XboxController::getLeftStickButtonPressed() {
    return getRawButtonPressed(Button::kLeftStick);
}

bool XboxController::getLeftStickButtonReleased() {
    return getRawButtonReleased(Button::kLeftStick);
}

BooleanEvent XboxController::leftStick(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getLeftStickButton(); });
}

bool XboxController::getRightStickButton() const {
    return getRawButton(Button::kRightStick);
}

bool XboxController::getRightStickButtonPressed() {
    return getRawButtonPressed(Button::kRightStick);
}

bool XboxController::getRightStickButtonReleased() {
    return getRawButtonReleased(Button::kRightStick);
}

BooleanEvent XboxController::rightStick(EventLoop *loop) const {
    return BooleanEvent(loop, [this]() { return this->getRightStickButton(); });
}

/*
bool XboxController::GetLeftBumper() const {
    return getRawButton(Button::kLeftBumper);
}

bool XboxController::GetRightBumper() const {
    return getRawButton(Button::kRightBumper);
}
*/

//bool XboxController::getLeftBumperButtonPressed() {
//    return getRawButtonPressed(Button::kLeftBumper);
//}
//
//bool XboxController::getRightBumperButtonPressed() {
//    return getRawButtonPressed(Button::kRightBumper);
//}
//
//bool XboxController::getLeftBumperButtonReleased() {
//    return getRawButtonReleased(Button::kLeftBumper);
//}
//
//bool XboxController::getRightBumperButtonReleased() {
//    return getRawButtonReleased(Button::kRightBumper);
//}
